### ISSUE TITLE
Make a 0.0.1 release on pypi

### ISSUE THREAD

**Issue by MridulS** [networkx/nx-parallel#11]
We should make a quick release on pypi to make sure we can tests this out more robustly.

**Comment by achluma** [comment]
Can I go ahead and publish a release?

**Comment by MridulS** [comment]
@achluma releases are to be made by one of the current maintainers so please don't put up anything on pypi :)

**Comment by achluma** [comment]
ok noted. thanks

**Comment by MridulS** [comment]
https://pypi.org/project/nx-parallel/0.1/ is out :)
