### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by spykelionel** [networkx/nx-parallel#22]
Most contributors face issues trying to run the project or generating a `heatmap_betweenness_centrality_timing.png` as a stated in [#191](https://github.com/networkx/outreachy/issues/191)

**Comment by Schefflera-Arboricola** [comment]
hi @spykelionel there will be a different infrastructure for benchmarking, it's a WIP (issue https://github.com/networkx/nx-parallel/issues/12). Also, in networkx the requirements files are auto-generated from the pyproject.toml file and not manually. So, you should consider making changes there, if any! 
for the outreachy task `pip install networkx matplotlib seaborn nx_parallel pandas` is enough ig.

Thank you :)

**Comment by spykelionel** [comment]
Thanks for the update @Schefflera-Arboricola. I have updated the requirements.txt to match the description above
